import React from 'react';
import { Leaf, Activity, Battery, Droplets, Wind } from 'lucide-react';

function Impact() {
  return (
    <div className="container" style={{ padding: '2rem 2rem 6rem' }}>
      <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
        <span className="tag-badge">Our Impact</span>
        <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>The Difference We Make</h1>
        <p style={{ color: 'var(--text-muted)', maxWidth: '600px', margin: '0 auto' }}>
          Every device you recycle contributes to a healthier planet. Here is a real-time dashboard of the positive environmental impact generated by the E-Cycle community.
        </p>
      </div>

      <div className="impact-section" style={{ marginTop: '0', padding: '4rem 0', borderRadius: 'var(--border-radius)' }}>
        <h2>Total E-Waste Prevented from Landfills</h2>
        <div className="impact-number" style={{ margin: '1rem 0' }}>12,450 <span style={{fontSize: '2rem'}}>Kg</span></div>
        <p style={{fontWeight: 600, color: 'var(--text-muted)'}}>And growing every single day</p>
      </div>

      <h3 style={{ margin: '4rem 0 2rem', textAlign: 'center', fontSize: '1.8rem' }}>Environmental Savings Breakdown</h3>

      <div className="cards-grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', gap: '1.5rem' }}>
        <div className="card highlight" style={{ padding: '2rem 1.5rem', alignItems: 'center', textAlign: 'center' }}>
          <Wind size={32} color="var(--primary)" style={{ marginBottom: '1rem' }} />
          <h2 style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>45.2T</h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', lineHeight: '1.2' }}>CO2 Emissions<br/>Prevented</p>
        </div>
        
        <div className="card" style={{ padding: '2rem 1.5rem', alignItems: 'center', textAlign: 'center' }}>
          <Battery size={32} color="#f59e0b" style={{ marginBottom: '1rem' }} />
          <h2 style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>8,200</h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', lineHeight: '1.2' }}>Toxic Batteries<br/>Safely Processed</p>
        </div>

        <div className="card highlight" style={{ padding: '2rem 1.5rem', alignItems: 'center', textAlign: 'center' }}>
          <Droplets size={32} color="#3b82f6" style={{ marginBottom: '1rem' }} />
          <h2 style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>1.2M</h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', lineHeight: '1.2' }}>Liters of Water<br/>Saved from Pollution</p>
        </div>

        <div className="card" style={{ padding: '2rem 1.5rem', alignItems: 'center', textAlign: 'center' }}>
          <Activity size={32} color="#8b5cf6" style={{ marginBottom: '1rem' }} />
          <h2 style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>125Kg</h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', lineHeight: '1.2' }}>Precious Metals<br/>Recovered</p>
        </div>
      </div>

      <div className="card" style={{ marginTop: '2rem', backgroundColor: 'var(--text-main)', color: 'white', display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <h3 style={{ color: 'white', marginBottom: '0.5rem' }}>Ready to contribute?</h3>
          <p style={{ color: '#aaa', margin: 0 }}>Join thousands of others in making our earth a cleaner place.</p>
        </div>
        <button className="pill-btn" style={{ backgroundColor: 'var(--primary)', color: 'white' }}>Start Recycling</button>
      </div>
    </div>
  );
}

export default Impact;
